server:
  port: 8081

spring:

  application:
    name: literary-association

  datasource:
    url: jdbc:mysql://localhost:3306/literary_association_db?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Belgrade
    username: root
    password: admin
    initialization-mode: always
    data: classpath:data.sql
    separator: ^;

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true
      connection:
        character-encoding: utf8
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.ticketist@gmail.com
    password: ticketist123
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          starttls.enable: true
          auth: true

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo

security:
  jwt:
    secret: most.secure.secret.ever
    lifetime: 604800

templates:
  html:
    verification: "verification"
    membership_request: "membership_request"

# TODO: File upload configuration
# TODO: File storage configuration
# TODO: HTML Templates