spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_camunda_lass?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo